[package]
name = "Mini_Project8_Yabei_Rust"
version = "0.1.0"
authors = ["Yabei Zeng"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rusqlite = "0.24"
reqwest = "0.11"
